[[targets]]
factor = 0.98057557
players = ["^o^ Fm$UD2EM@KODU大好人"]

[[targets]]
factor = 0.98244480
players = ["⑨-MXgoCOds6Glu@新纪元"]

[[targets]]
factor = 0.98569075
players = ["1^GNC.%F@Hell"]

[[targets]]
factor = 0.98672652
players = ["智障 YRj4wIzaR5s1@Afterglow"]

[[targets]]
factor = 0.98889011
players = ["Orbital #sfPTzSpZz@tyakasha"]

[[targets]]
factor = 0.98861797
players = ["Wispy #6uttTRg@Arcadia"]

[[targets]]
factor = 0.98862525
players = ["伊甸 en5QiIQ?shadow@魔"]

[[targets]]
factor = 0.99212506
players = ["星辰魔术 747995597493@Squall"]

[[targets]]
factor = 0.98990637
players = ["芳縼乌菈 🂷🂭🃇🂭🃞🃜🂫@四象柯"]

[[targets]]
factor = 0.99009886
players = ["酥皮浓汤 #02eev5fa@爱"]

[[targets]]
factor = 0.99124138
players = ["Iridia_Noctiluca #6H9Vt9Bd@Nexus_Mirabilis"]

[[targets]]
factor = 0.99351477
players = ["故障机器人 #VJCLMOZPE@暗黑突击"]

[[targets]]
factor = 0.99541359
players = ["Bascor cW1JWDuv7f@RbCl"]

[[targets]]
factor = 0.99402303
players = ["Hell 迚昫餅@名字竞技场"]

[[targets]]
factor = 0.99508402
players = ["Tirn y_[yNJ#jq\"9r@流浪冒险者"]

[[targets]]
factor = 0.99509193
players = ["镜华 CWXJVQRP@公主连结"]

[[targets]]
factor = 0.99904186
players = ["上山岗 DXACQPRRC@LuoTianyi"]

[[targets]]
factor = 1.00120127
players = ["Kuouji_alice fEhChpbSwh@🥒"]
