[[targets]]
factor = 0.98070813
players = ["Tik_Tok #IBxWzGZtr@Shabby_fish"]

[[targets]]
factor = 0.98099985
players = ["0000006NTVJWbvH@aaa"]

[[targets]]
factor = 0.98405566
players = ["秋菊 mcrP7gX?shadow@魔"]

[[targets]]
factor = 0.98731347
players = ["花语堂夜 #OHKFKDOOI@无惨"]

[[targets]]
factor = 0.98602230
players = ["黎明叙事 677097391180@Squall"]

[[targets]]
factor = 0.98793355
players = ["灀瑈篆狓鵃@四象柯"]

[[targets]]
factor = 0.98712122
players = ["涂愿烄鮈鵢@四象柯"]

[[targets]]
factor = 0.99246281
players = ["沓颊 LCI2QNZ5@Squall"]

[[targets]]
factor = 0.99001968
players = ["<ημ>-nfw5ezna@ReturnVoid"]

[[targets]]
factor = 0.99044987
players = ["九十九八桥 6G6GIGLI@Squall"]

[[targets]]
factor = 0.99398390
players = ["雾山惟助 BAAOVADZ@TigerStar"]

[[targets]]
factor = 0.99236352
players = ["三头区 #NYmDCMu3g@！？区猴猴区？！"]

[[targets]]
factor = 0.99579975
players = ["七岔要塞 -A8PT6j3aIl-@新纪元"]

[[targets]]
factor = 0.99443846
players = ["怚驵細驵阻岨䧃佃畑畑趄蛆@涵虚"]

[[targets]]
factor = 0.99467978
players = ["тцчяёсюфъ@新纪元"]

[[targets]]
factor = 0.99538568
players = ["前尘如梦 UYGMHRNX@LuoTianyi"]

[[targets]]
factor = 0.99948128
players = ["莉莉霍瓦特 H9UEBBVD@Squall"]

[[targets]]
factor = 0.99803457
players = ["青冈00397016962394@abruce"]

[[targets]]
factor = 0.99994490
players = ["00000052qRHvFoy@aaa"]

[[targets]]
factor = 0.99527040
players = ["静影WZBMCVWUF@涵虚"]

[[targets]]
factor = 0.99964740
players = ["回天zy33FFARg@candle"]

[[targets]]
factor = 0.99648918
players = ["五字神人 #02f5lSWo@爱"]

[[targets]]
factor = 1.00017117
players = ["0000003FzAO7HhL@aaa"]

[[targets]]
factor = 1.00053784
players = ["Antonio_Salieri #ytpPxakBZd@🥒"]

[[targets]]
factor = 1.00185109
players = ["霨謹橵蚒孰@四象柯"]

[[targets]]
factor = 1.00298428
players = ["Mira_Hacia_El_Cielo #gJEftkUaX@Shabby_fish"]

[[targets]]
factor = 1.00037560
players = ["ernie-5.0-thinking-preview #CfmvP0rX0@Shabby_fish"]

[[targets]]
factor = 1.00419612
players = ["0000001YcQMZjkz@aaa"]

[[targets]]
factor = 1.00353746
players = ["栀之神力 🃎🃏🂥🃛🂨🃘🂱@四象柯"]

[[targets]]
factor = 1.00291092
players = ["神玉 E4ILFVGO@Squall"]

[[targets]]
factor = 1.00260479
players = ["席尔娜 nkkP4td@无惨"]

[[targets]]
factor = 1.00106302
players = ["Arcueid LfsxCJYLuj@🥒"]

[[targets]]
factor = 1.00777526
players = ["1h([HliV@Hell"]

[[targets]]
factor = 1.00890023
players = ["insanity#lPJr7ajyBTz6NWXeuMiL@czr2012"]

[[targets]]
factor = 1.00807405
players = ["神户旭 $06WqS73U@爱"]

[[targets]]
factor = 1.00870474
players = ["緋色のDance #hUxfUgcfAp@🥒"]
