[[targets]]
factor = 0.98134210
players = ["银铃歌者.流花燕 \\!}G2F0Z/@四象柯"]

[[targets]]
factor = 0.98989117
players = ["萨丽爱尔 IELUALOU@Squall"]

[[targets]]
factor = 0.99110882
players = ["0000004zsX0ITJH@aaa"]

[[targets]]
factor = 0.99344004
players = ["milkΙлЯωΦПΞΣъЭ@lzk"]

[[targets]]
factor = 0.99552466
players = ["'Yz|AS}@Hell"]

[[targets]]
factor = 0.99453753
players = ["とツウヨゆプピリうくぱニのずぐぶちテろえウ@Squall"]

[[targets]]
factor = 0.99538568
players = ["前尘如梦 UYGMHRNX@LuoTianyi"]

[[targets]]
factor = 0.99821688
players = ["リズと青い鳥 #GDatSLaSpu@🥒"]

[[targets]]
factor = 0.99739797
players = ["平行線 #DyeDWKthAL@🥒"]

[[targets]]
factor = 0.99820436
players = ["咒冲 557624508459@Squall"]

[[targets]]
factor = 1.00024674
players = ["咲夜 oswFmWcG@Squall"]

[[targets]]
factor = 1.00025686
players = ["该玩家已挂机，点此跳过他的回合 OQAf07JZxq@XJ联队"]

[[targets]]
factor = 0.99731589
players = ["Soudelor VGDAEAHOJNQY@nan"]

[[targets]]
factor = 0.99831256
players = ["Beijing_Beijing #buBfAkjNf@Shabby_fish"]

[[targets]]
factor = 1.00045256
players = ["ΦAOwxwKTN@ssg"]

[[targets]]
factor = 0.99680065
players = ["System_shutdown #vHatYzLOtM@🥒"]

[[targets]]
factor = 1.00129760
players = ["0000003AeTw5YVJ@aaa"]

[[targets]]
factor = 0.99834450
players = ["Kotori jVg4KQW5h@candle"]

[[targets]]
factor = 1.00142898
players = ["烟烟罗 9EHPRV2T@Squall"]

[[targets]]
factor = 1.00267285
players = ["あはらけぷまぬ@新纪元"]

[[targets]]
factor = 1.00119073
players = ["五箭谏函哄@昀澤"]

[[targets]]
factor = 1.00356124
players = ["百合IQ180 916973361557@Squall"]

[[targets]]
factor = 1.00155161
players = ["CtC7gL9JNpvNpOl@新纪元"]

[[targets]]
factor = 1.00507163
players = ["SIN_BA-NELRTUTMI4JNEBF@Squall"]

[[targets]]
factor = 1.00420817
players = ["夏 rgPbhssrqs91@Afterglow"]
