[[targets]]
factor = 0.98070813
players = ["Tik_Tok #IBxWzGZtr@Shabby_fish"]

[[targets]]
factor = 0.98099985
players = ["0000006NTVJWbvH@aaa"]

[[targets]]
factor = 0.98405566
players = ["秋菊 mcrP7gX?shadow@魔"]

[[targets]]
factor = 0.98731347
players = ["花语堂夜 #OHKFKDOOI@无惨"]

[[targets]]
factor = 0.98712122
players = ["涂愿烄鮈鵢@四象柯"]

[[targets]]
factor = 0.98679206
players = ["0000005WuxfrjJ0@aaa"]

[[targets]]
factor = 0.98725438
players = ["竞唆芳杰@Hell"]

[[targets]]
factor = 0.98742975
players = ["Straight_into_the_lights #VpdbCrcFJV@🥒"]

[[targets]]
factor = 0.99110882
players = ["0000004zsX0ITJH@aaa"]

[[targets]]
factor = 0.98951429
players = ["Estahv tB57MelvI@candle"]

[[targets]]
factor = 0.99344004
players = ["milkΙлЯωΦПΞΣъЭ@lzk"]

[[targets]]
factor = 0.99159033
players = ["血遁 65#inkQQX@仙蛊屋"]

[[targets]]
factor = 0.99026671
players = ["<γρ>-xthyizh5@ReturnVoid"]

[[targets]]
factor = 0.99453753
players = ["とツウヨゆプピリうくぱニのずぐぶちテろえウ@Squall"]

[[targets]]
factor = 0.99545975
players = ["姬塔 #XZEICGHHO@暗黑突击"]

[[targets]]
factor = 0.99471926
players = ["Obsession #EYNIZRX@Unbound"]

[[targets]]
factor = 0.99519352
players = ["<ηψ>-bjdrswie@ReturnVoid"]

[[targets]]
factor = 0.99565434
players = ["Iridia_Noctiluca #9qGjK1sq@Nexus_Mirabilis"]

[[targets]]
factor = 0.99894834
players = ["土豆不等式 QPBPMQNW@Squall"]
