[[targets]]
factor = 1.255339401484
players = ["Tik_Tok #IBxWzGZtr@Shabby_fish"]

[[targets]]
factor = 1.349116834816
players = ["涵虚不等式 PFVKEUPBU@TigerStar"]

[[targets]]
factor = 1.215240204656
players = ["Ⅹ q5H2HO5@新纪元"]

[[targets]]
factor = 1.579395694784
players = ["\\HandsInTheFire\\-899252857203@\\XIV\\-14"]

[[targets]]
factor = 1.145560219366
players = ["天依 'i[8S`Aw@LuoTianyi"]

[[targets]]
factor = 1.234503706816
players = ["0000006NTVJWbvH@aaa"]

[[targets]]
factor = 1.141322294400
players = ["跙坥咀诅阻珇伹伹怚@涵虚"]

[[targets]]
factor = 1.064187377468
players = ["虚空托腮 IVHEWTNEA@TigerStar"]

[[targets]]
factor = 1.050372435186
players = ["喘际瞬爆@昀澤"]

[[targets]]
factor = 1.251793167094
players = ["前尘如梦 UYGMHRNX@LuoTianyi"]

[[targets]]
factor = 1.233647917892
players = ["7aKO XkQ@Nexus_Mirabilis"]

[[targets]]
factor = 1.320291891752
players = ["リズと青い鳥 #GDatSLaSpu@🥒"]

[[targets]]
factor = 1.248415759175
players = ["杀 amUrtLhpqzFq@Afterglow"]

[[targets]]
factor = 1.210987093008
players = ["失温滢霞.寂静蓝 `f.Gi\\Z:R@四象柯"]

[[targets]]
factor = 1.008076445602
players = ["一人行者 Da22adc4bC2B@LuoTianyi"]

[[targets]]
factor = 1.057418535994
players = ["沺岨伹䟧姐坥狙柤柤粗鈿伹@涵虚"]

[[targets]]
factor = 1.156158937086
players = ["蕾蒂·怀特洛可-65HEZHB264LFPFQ@Squall"]

[[targets]]
factor = 1.053864829902
players = ["十六夜咲夜 imIuZYJk@Squall"]

[[targets]]
factor = 1.263478019193
players = ["解 c5hlvevqciBk@Afterglow"]

[[targets]]
factor = 1.380586134578
players = ["席尔娜 nkkP4td@无惨"]

[[targets]]
factor = 1.394509937355
players = ["不知者 OTKJAHHBM@LuoTianyi"]

[[targets]]
factor = 1.102836138268
players = ["涵虚abrfxfx黄瓜a0smdda0smddsmdd阿郎新纪元@名字竞技场"]

[[targets]]
factor = 1.192812473965
players = ["鑺掕悂 R9feo6cEJ4Aj@芒萁"]

[[targets]]
factor = 0.903931098663
players = ["睦 laqkDvDuCZ@🥒"]

[[targets]]
factor = 1.370956263137
players = ["Imperio #IZIYGpKZ@Shabby_fish"]

[[targets]]
factor = 0.990485176844
players = ["Meranti FBPITYXTBPQG@nan"]

[[targets]]
factor = 1.190692910640
players = ["Tachibana_kanade #ipOjmvSKQy@🥒"]

[[targets]]
factor = 0.945370850833
players = ["<λγ>-arrc7pg1@ReturnVoid"]

[[targets]]
factor = 0.708839018713
players = ["稗田阿求-UU4Q3YPGL84QO1G@Squall"]

[[targets]]
factor = 1.171865402985
players = ["𝞮𝞯𝞻𝞸𝞰𝞮𝞸𝞳@昀澤"]

[[targets]]
factor = 1.013224931310
players = ["艾泽莉娅 #DANOKVKIUZ@无惨"]

[[targets]]
factor = 1.038523111447
players = ["谁敢挡路，揍他 qACN0KQVqgpROQY@TigerStar"]

[[targets]]
factor = 1.184271521187
players = ["Momomomo #YAORzaY@Arcadia"]

[[targets]]
factor = 0.818317457461
players = ["射却S4z1tff7m@candle"]

[[targets]]
factor = 0.794633428255
players = ["Aihara_tsubaki #XFwTfrRbZw@🥒"]

[[targets]]
factor = 0.956066548084
players = ["飞雪PSODKKXWP@涵虚"]

[[targets]]
factor = 0.863813302650
players = ["秋菊 mcrP7gX?shadow@魔"]

[[targets]]
factor = 0.499838877380
players = ["自傷無色 #DpPzLuVmWe@🥒"]

[[targets]]
factor = 0.831357083910
players = ["芳寒滢.霜栀痛魔 S/*`kms`6@四象柯"]

[[targets]]
factor = 0.717863142944
players = ["0000001p5tE2pMs@aaa"]

[[targets]]
factor = 0.671017219650
players = ["Momo #L9GHU8F@Arcadia"]

[[targets]]
factor = 1.019181669330
players = ["milkΙлЯωΦПΞΣъЭ@lzk"]

[[targets]]
factor = 0.863070534340
players = ["黄陆汹聊级神秘战巡舰@巡洋舰"]

[[targets]]
factor = 0.441666127458
players = ["1Reh>\\Ma@Hell"]

[[targets]]
factor = 0.383494937028
players = ["00000052qRHvFoy@aaa"]

[[targets]]
factor = 0.538960500734
players = ["Rin opTSeXM3V@candle"]

[[targets]]
factor = 0.753547340038
players = ["00000000MOYffOK@aaa"]

[[targets]]
factor = 0.506254812220
players = ["Limit1-608000844Lillia@shadowT"]

[[targets]]
factor = 0.593220779040
players = ["溯桤蛥赢，加一昏@爱"]

[[targets]]
factor = 0.319620503878
players = ["育欢学诀@Hell"]
