[[targets]]
factor = 1.322948538291
players = ["黎明叙事 677097391180@Squall", "沓颊 LCI2QNZ5@Squall"]

[[targets]]
factor = 1.346150164347
players = ["⑨-MXgoCOds6Glu@新纪元", "ⅺ Hf3Yqb4@新纪元"]

[[targets]]
factor = 1.848546899756
players = ["Parma KKMJDZDJPYBW@nan", "Saomai BFFVJMEIFRCK@nan"]

[[targets]]
factor = 0.875743033119
players = ["青霉素 #gRybM8geD@Shabby_fish", "Tik_Tok #IBxWzGZtr@Shabby_fish"]

[[targets]]
factor = 0.610722617891
players = ["Orbital #sfPTzSpZz@tyakasha", "H6PeQOTNUlx@tyakasha"]

[[targets]]
factor = 1.205618614283
players = ["世末积雨云 MEENDWBQU@LuoTianyi", "大氿歌 FESNBZBOJ@LuoTianyi"]

[[targets]]
factor = 0.390173837676
players = ["一对笑面虎 my7CAxNHHz@XJ联队", "2LRLYnOw5pmmhXG@XJ联队"]

[[targets]]
factor = 0.328175264803
players = ["智障 YRj4wIzaR5s1@Afterglow", "nXAsBGsjpc8t@Afterglow"]

[[targets]]
factor = 0.172957861815
players = ["渡里贝子 TJZMB3ZF@Squall", "萨丽爱尔 IELUALOU@Squall"]

[[targets]]
factor = 0.468129185104
players = ["ilem ?MJxj\u0026\u003c^@LuoTianyi", "前尘如梦 UYGMHRNX@LuoTianyi"]

[[targets]]
factor = 0.286156482206
players = ["錦帆 #hF0kQwdQp@Shabby_fish", "Italian_Love #5Agn8kVYl@Shabby_fish"]

[[targets]]
factor = 0.404681162365
players = ["艾泽莉娅 #sDEeWv1@无惨", "花语堂夜 #OHKFKDOOI@无惨"]

[[targets]]
factor = 2.404757236863
players = ["1^GNC.%F@Hell", "1f67~3l}@Hell"]

[[targets]]
factor = 0.513105097391
players = ["风驰-xtxxgwcb@涵虚", "潮汐-糖藷愠颏@涵虚"]

[[targets]]
factor = 0.010000000000
players = ["碧歧砚杭@昀澤", "愞㢯老海@昀澤"]

[[targets]]
factor = 0.998054668274
players = ["0000001k0cMp9JI@aaa", "0000001DuKtKYYr@aaa"]

[[targets]]
factor = 0.173386692245
players = ["\u003cηω\u003e-mf5uz2u5@ReturnVoid", "\u003cζο\u003e-2ny1o5sk@ReturnVoid"]

[[targets]]
factor = 0.393827277897
players = ["灀瑈篆狓鵃@四象柯", "冷酷.僵直 cVh|1;Rl@四象柯"]

[[targets]]
factor = 0.206260225059
players = ["Nepartak XJZBUIDVDDCX@nan", "Fengshen ONVWTGMPNCKV@nan"]

[[targets]]
factor = 1.919785800166
players = ["咲夜 bJjbFYez@Squall", "SIN_BA-NELRTUTMI4JNEBF@Squall"]

[[targets]]
factor = 1.666016126118
players = ["九十九八桥 6G6GIGLI@Squall", "稗田阿求 OQL68NN8@Squall"]

[[targets]]
factor = 1.467573560860
players = ["豹邻跑恒 #ytRNzqQCmO@🥒", "Wakaba_mutsumi #WDmikbTndr@🥒"]

[[targets]]
factor = 0.010000000000
players = ["\u003cζε\u003e-fhepgq2n@ReturnVoid", "\u003cδγ\u003e-2y8tkiju@ReturnVoid"]

[[targets]]
factor = 1.246557060459
players = ["仇决clFJZCMHS@candle", "Sorrowless 2nafI0zFE@candle"]

[[targets]]
factor = 0.247252056366
players = ["000000039BXLGdc@aaa", "0000002Aft3uuC5@aaa"]

[[targets]]
factor = 1.669298593851
players = ["涵虚不等式 PFVKEUPBU@TigerStar", "三猴一体 vFz1cu21MCaW@TigerStar"]

[[targets]]
factor = 0.334068633047
players = ["致我所爱的你 /jOeI3BL9vX/@新纪元", "TAG #230182204122@新纪元"]

[[targets]]
factor = 1.728691494098
players = ["тцчяёсюфъ@新纪元", "⑦ KR3K0bY@新纪元"]

[[targets]]
factor = 0.663726245407
players = ["牙四 xX4hHzW@fx", "三田一重 TxtrdTN4l8nT@fx"]

[[targets]]
factor = 1.794155918007
players = ["自傷無色 #hppypcGNKF@🥒", "Straight_into_the_lights #VpdbCrcFJV@🥒"]

[[targets]]
factor = 0.947496690856
players = ["权计WN13vmJnn@candle", "谣诼IWxur5C4t@candle"]

[[targets]]
factor = 0.525319288385
players = ["无限热情 /CIG0mdjNEF/@新纪元", "歌者之印 /fvQbAhVRyC/@新纪元"]

[[targets]]
factor = 1.488433826092
players = ["\u003cγω\u003e-91zuonbf@ReturnVoid", "\u003cηψ\u003e-bjdrswie@ReturnVoid"]

[[targets]]
factor = 1.402763385726
players = ["镜湖TVWAFPFHB@涵虚", "田柤钿坥畑租鉏组佃怚钿组@涵虚"]

[[targets]]
factor = 1.578780749906
players = ["雾山惟助 BAAOVADZ@TigerStar", "锋利Ⅴ EGZPVQMY@TigerStar"]

[[targets]]
factor = 1.132476590930
players = ["0000000RsY6L2Wn@aaa", "0000005dj3ealJd@aaa"]

[[targets]]
factor = 0.834621112542
players = ["星辰魔术 747995597493@Squall", "とツウヨゆプピリうくぱニのずぐぶちテろえウ@Squall"]

[[targets]]
factor = 1.849865236964
players = ["➎-KGlQCm7n9qNB@新纪元", "“乌鸦爵士”波里斯 -D5W5NLSFZU-@新纪元"]

[[targets]]
factor = 1.371341553855
players = ["伊甸 en5QiIQ?shadow@魔", "秋菊 mcrP7gX?shadow@魔"]

[[targets]]
factor = 0.534835952372
players = ["随之任之 #sBhIKqkNgF@🥒", "Tsujikura_Spica #lmThcBVTES@🥒"]

[[targets]]
factor = 0.884605366636
players = ["Tachibana_akira #BydbIMidbs@🥒", "Scene_shifts_there #uJeRDMdsAU@🥒"]

[[targets]]
factor = 1.397063232134
players = ["冥河 WyO8MUZPPtKH@Afterglow", "光 jKLA6V5mirfs@Afterglow"]

[[targets]]
factor = 1.735022762634
players = ["百合IQ180 916973361557@Squall", "幻月 0HPYJDW8@Squall"]

[[targets]]
factor = 1.243146468931
players = ["吸血魔兽 #OPZDENED@暗黑突击", "神谷紫苑 #EUKSOXAA@暗黑突击"]

[[targets]]
factor = 1.077497356025
players = ["goldenfield #FrffnWttdH@🥒", "God_knows... #phowbIlpwv@🥒"]

[[targets]]
factor = 1.743135927857
players = ["00000040k0wLBzO@aaa", "00000071Ed65lDS@aaa"]

[[targets]]
factor = 1.130472041734
players = ["0000005TMW40n9m@aaa", "0000006NTVJWbvH@aaa"]

[[targets]]
factor = 1.155791199986
players = ["0000003FzAO7HhL@aaa", "0000004zsX0ITJH@aaa"]

[[targets]]
factor = 0.620331535724
players = ["Miki_sayaka #UcmbwBTszI@🥒", "Antonio_Salieri #ytpPxakBZd@🥒"]

[[targets]]
factor = 0.640479372338
players = ["Sennoza i7kkPtoDTQ@RbCl", "Waking_Shadows LwxfyIzwjI@RbCl"]
