[[targets]]
factor = 1.342731918759
players = ["skywork-13b #0w1cbREuh@Shabby_fish", "Tik_Tok #IBxWzGZtr@Shabby_fish"]

[[targets]]
factor = 1.221161982354
players = ["黎明叙事 677097391180@Squall", "沓颊 LCI2QNZ5@Squall"]

[[targets]]
factor = 1.179537759445
players = ["Parma KKMJDZDJPYBW@nan", "Saomai BFFVJMEIFRCK@nan"]

[[targets]]
factor = 1.215675447066
players = ["世末积雨云 MEENDWBQU@LuoTianyi", "大氿歌 FESNBZBOJ@LuoTianyi"]

[[targets]]
factor = 0.771707798161
players = ["⑨-MXgoCOds6Glu@新纪元", "ⅺ Hf3Yqb4@新纪元"]

[[targets]]
factor = 0.954670664899
players = ["一对笑面虎 my7CAxNHHz@XJ联队", "2LRLYnOw5pmmhXG@XJ联队"]

[[targets]]
factor = 1.136601989839
players = ["渡里贝子 TJZMB3ZF@Squall", "萨丽爱尔 IELUALOU@Squall"]

[[targets]]
factor = 1.221446709089
players = ["Orbital #sfPTzSpZz@tyakasha", "H6PeQOTNUlx@tyakasha"]

[[targets]]
factor = 1.106545523167
players = ["1^GNC.%F@Hell", "1f67~3l}@Hell"]

[[targets]]
factor = 0.986317735964
players = ["艾泽莉娅 #sDEeWv1@无惨", "花语堂夜 #OHKFKDOOI@无惨"]

[[targets]]
factor = 0.922773387821
players = ["ilem ?MJxj&<^@LuoTianyi", "前尘如梦 UYGMHRNX@LuoTianyi"]

[[targets]]
factor = 0.969121615261
players = ["0000001k0cMp9JI@aaa", "0000001DuKtKYYr@aaa"]

[[targets]]
factor = 0.921030106310
players = ["錦帆 #hF0kQwdQp@Shabby_fish", "Italian_Love #5Agn8kVYl@Shabby_fish"]

[[targets]]
factor = 0.990731740027
players = ["Saeki_sayaka #ihzmDmwsho@🥒", "緋色のDance #hUxfUgcfAp@🥒"]

[[targets]]
factor = 1.290490726575
players = ["智障 YRj4wIzaR5s1@Afterglow", "nXAsBGsjpc8t@Afterglow"]

[[targets]]
factor = 1.119109489633
players = ["百合IQ180 916973361557@Squall", "约伦·蕾恩·里德韦尔德 864903811148@Squall"]

[[targets]]
factor = 1.163697257014
players = ["тцчяёсюфъ@新纪元", "⑦ KR3K0bY@新纪元"]

[[targets]]
factor = 1.305161156455
players = ["九十九八桥 6G6GIGLI@Squall", "稗田阿求 OQL68NN8@Squall"]

[[targets]]
factor = 1.303774301085
players = ["风驰-xtxxgwcb@涵虚", "潮汐-糖藷愠颏@涵虚"]

[[targets]]
factor = 1.178910665339
players = ["Tachibana_akira #BydbIMidbs@🥒", "透明な海 #qFIRwpGNOd@🥒"]

[[targets]]
factor = 1.298191039379
players = ["豹邻跑恒 #ytRNzqQCmO@🥒", "Wakaba_mutsumi #WDmikbTndr@🥒"]

[[targets]]
factor = 0.895386628350
players = ["灀瑈篆狓鵃@四象柯", "冷酷.僵直 cVh|1;Rl@四象柯"]

[[targets]]
factor = 0.875202944629
players = ["权计WN13vmJnn@candle", "Rewrite 7CQd5C23F@candle"]

[[targets]]
factor = 0.550213067582
players = ["咲夜 bJjbFYez@Squall", "SIN_BA-NELRTUTMI4JNEBF@Squall"]

[[targets]]
factor = 0.902363134263
players = ["镜湖TVWAFPFHB@涵虚", "田柤钿坥畑租鉏组佃怚钿组@涵虚"]

[[targets]]
factor = 1.146154461392
players = ["Nepartak XJZBUIDVDDCX@nan", "Fengshen ONVWTGMPNCKV@nan"]

[[targets]]
factor = 0.953596462782
players = ["<ζε>-fhepgq2n@ReturnVoid", "<δγ>-2y8tkiju@ReturnVoid"]

[[targets]]
factor = 1.145983465074
players = ["<ηω>-mf5uz2u5@ReturnVoid", "<ζο>-2ny1o5sk@ReturnVoid"]

[[targets]]
factor = 1.172822626458
players = ["伊甸 en5QiIQ?shadow@魔", "秋菊 mcrP7gX?shadow@魔"]

[[targets]]
factor = 1.009333778338
players = ["牙四 xX4hHzW@fx", "三田一重 TxtrdTN4l8nT@fx"]

[[targets]]
factor = 0.931892423896
players = ["仇决clFJZCMHS@candle", "Sorrowless 2nafI0zFE@candle"]

[[targets]]
factor = 0.991893127943
players = ["无限热情 /CIG0mdjNEF/@新纪元", "歌者之印 /fvQbAhVRyC/@新纪元"]

[[targets]]
factor = 0.708860818427
players = ["自傷無色 #hppypcGNKF@🥒", "Straight_into_the_lights #VpdbCrcFJV@🥒"]

[[targets]]
factor = 0.869833824663
players = ["<γω>-91zuonbf@ReturnVoid", "<ηψ>-bjdrswie@ReturnVoid"]

[[targets]]
factor = 0.869349008238
players = ["000000039BXLGdc@aaa", "0000002Aft3uuC5@aaa"]

[[targets]]
factor = 1.112999680243
players = ["0000000RsY6L2Wn@aaa", "0000005dj3ealJd@aaa"]

[[targets]]
factor = 1.029761312359
players = ["四风判词 SDTCKJJYY@LuoTianyi", "春风来 HLSKCEFAT@LuoTianyi"]

[[targets]]
factor = 1.263335615968
players = ["浆洿辳瘸詯@四象柯", "结晶萤灰滢 🃈🂤🃒🃎🂵🃋🂺@四象柯"]

[[targets]]
factor = 0.884777278812
players = ["上山岗 DXACQPRRC@LuoTianyi", "上山岗 SHSBGNXBW@LuoTianyi"]

[[targets]]
factor = 1.197418172466
players = ["涵虚不等式 PFVKEUPBU@TigerStar", "三猴一体 vFz1cu21MCaW@TigerStar"]

[[targets]]
factor = 0.989234726800
players = ["Accio #LD5MtqO8@Shabby_fish", "喘息之机 #fZQJ6LHzs@Shabby_fish"]

[[targets]]
factor = 0.459891783610
players = ["春归 #AzKpHrQnMY@🥒", "ポケットをふくらませて~ #PwoRpIIwgw@🥒"]

[[targets]]
factor = 0.951469628788
players = ["玷裙染.无眠 w|W(Z71S@四象柯", "银铃歌者.流花燕 \\!}G2F0Z/@四象柯"]

[[targets]]
factor = 1.017646210694
players = ["⑥ nR-TB89@新纪元", "Ⅻ-C9uFmDObJS6a@新纪元"]

[[targets]]
factor = 0.971239303299
players = ["雾山惟助 BAAOVADZ@TigerStar", "锋利Ⅴ EGZPVQMY@TigerStar"]

[[targets]]
factor = 0.899208453210
players = ["七岔要塞 -A8PT6j3aIl-@新纪元", "➏ 2BD-6=W@新纪元"]

[[targets]]
factor = 1.237156904669
players = ["力量 2#pfiD1t@仙蛊屋", "行空 29#tTfIBV@仙蛊屋"]

[[targets]]
factor = 0.309367854964
players = ["二阶堂希罗 1RCcDJR8yR1@无惨", "樱井光 #EVBIKHRIGNWH@无惨"]

[[targets]]
factor = 0.847258790183
players = ["0000003sbxSc0Xy@aaa", "0000004rYcndKOh@aaa"]

[[targets]]
factor = 0.206959498257
players = ["双向 UFFLYDJJE@LuoTianyi", "无理无智 MJTEZIUCQ@LuoTianyi"]
