[package]
name = "tswn_openbox"
description = "A simple interactive panel for common tswn tools"
version = "0.4.1"
edition = "2024"

[dependencies]
eframe = "0.36.1"
rfd = "0.17.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "1.1.4"
tswn_core = { path = "../tswn_core", default-features = false, features = ["no_debug", "png_render"] }

[features]
default = ["mimalloc_alloc"]
no_debug = ["tswn_core/no_debug"]
mimalloc_alloc = ["tswn_core/mimalloc_alloc"]
