[[targets]]
factor = 0.98353640
players = ["ilem ?MJxj&<^@LuoTianyi"]

[[targets]]
factor = 0.98989117
players = ["萨丽爱尔 IELUALOU@Squall"]

[[targets]]
factor = 0.98647948
players = ["Accio #LD5MtqO8@Shabby_fish"]

[[targets]]
factor = 0.98969283
players = ["luogu.com.cn/paste/q9h8sdzk@Shabby_fish"]

[[targets]]
factor = 0.99483669
players = ["涵虚不等式 PFVKEUPBU@TigerStar"]

[[targets]]
factor = 0.99585652
players = ["<ζε>-fhepgq2n@ReturnVoid"]

[[targets]]
factor = 0.99647444
players = ["随之任之 #mDEGkQOkOd@🥒"]

[[targets]]
factor = 0.99636094
players = ["<θτ>-unf9q559@ReturnVoid"]

[[targets]]
factor = 0.99677090
players = ["Iridia_Noctiluca #6kb5skxS@Nexus_Mirabilis"]

[[targets]]
factor = 0.99978655
players = ["Felix CQACSVGRXSAT@nan"]

[[targets]]
factor = 0.99948128
players = ["莉莉霍瓦特 H9UEBBVD@Squall"]

[[targets]]
factor = 1.00157506
players = ["↙️⬅️⤵️⬇️⬆️↩️⤵️➡️⬅️↩️↙️⤴️@新纪元"]

[[targets]]
factor = 1.00055184
players = ["0000002UeTboJTR@aaa"]

[[targets]]
factor = 0.99827376
players = ["慧剑 IZ2X35uT8wVt@Afterglow"]

[[targets]]
factor = 1.00138752
players = ["力气 30#zxQ4y6@仙蛊屋"]

[[targets]]
factor = 1.00220952
players = ["拟光 547334214552@Squall"]

[[targets]]
factor = 1.00029252
players = ["糍粑姐 #06fJFRN2@爱"]

[[targets]]
factor = 1.00129454
players = ["無名惰蛾衣肮@神之长子leo"]

[[targets]]
factor = 1.00155161
players = ["CtC7gL9JNpvNpOl@新纪元"]

[[targets]]
factor = 1.00310768
players = ["我没在炼你，我在ber你 #08DpCnEa@爱"]

[[targets]]
factor = 1.00517601
players = ["Immutable ZYsdlabOOz@RbCl"]

[[targets]]
factor = 1.00801915
players = ["syVS:et@Hell"]
