"""RC4 类型存根。"""

class RC4:
    """RC4 随机数与加解密接口。"""
    def __init__(self, keys: bytes, round: int | None = 1) -> None:
        """使用 key 初始化 RC4。"""
        ...
    @staticmethod
    def val_len() -> int:
        """返回 S 盒长度。"""
        ...
    @property
    def i(self) -> int:
        """RC4 状态变量 `i`。"""
        ...
    @i.setter
    def i(self, val: int) -> None:
        """设置 RC4 状态变量 `i`。"""
        ...
    @property
    def j(self) -> int:
        """RC4 状态变量 `j`。"""
        ...
    @j.setter
    def j(self, val: int) -> None:
        """设置 RC4 状态变量 `j`。"""
        ...
    def get_val(self) -> bytes:
        """返回完整 S 盒。"""
        ...
    def get_val_at(self, index: int) -> int:
        """读取指定下标字节。"""
        ...
    def set_val_at(self, index: int, value: int) -> None:
        """设置指定下标字节。"""
        ...
    def update(self, keys: bytes, round: int | None = 1) -> None:
        """基于 key 更新当前状态。"""
        ...
    def xor_bytes(self, data: bytes) -> bytes:
        """对字节串执行 XOR。"""
        ...
    def js_xor_bytes(self, data: bytes) -> bytes:
        """按 JS 兼容语义执行 XOR。"""
        ...
    def xor_str(self, text: str) -> None:
        """对字符串执行 XOR。"""
        ...
    def js_xor_str(self, text: str) -> None:
        """按 JS 兼容语义对字符串执行 XOR。"""
        ...
    def encrypt_bytes(self, data: bytes) -> bytes:
        """加密字节串。"""
        ...
    def encrypt_bytes_no_change(self, text: str) -> None:
        """在不改输入缓冲的语义下加密字符串。"""
        ...
    def decrypt_bytes(self, data: bytes) -> bytes:
        """解密字节串。"""
        ...
    def next_u8(self) -> int:
        """生成下一个随机字节。"""
        ...
    def next_i32(self, max: int) -> int:
        """生成 `[0, max)` 范围随机数。"""
        ...
    def round(self, keys: bytes, round: int | None = 1) -> None:
        """重置后执行 round 混洗。"""
        ...
    def peek_next_u8(self) -> int:
        """查看下一个随机字节但不推进状态。"""
        ...
    def c94(self) -> bool:
        """返回约 94% 概率为真的随机结果。"""
        ...
    def c75(self) -> bool:
        """返回约 75% 概率为真的随机结果。"""
        ...
    def c50(self) -> bool:
        """返回约 50% 概率为真的随机结果。"""
        ...
    def c25(self) -> bool:
        """返回约 25% 概率为真的随机结果。"""
        ...
    def c12(self) -> bool:
        """返回约 12% 概率为真的随机结果。"""
        ...
    def c33(self) -> bool:
        """返回约 33% 概率为真的随机结果。"""
        ...
    def c66(self) -> bool:
        """返回约 66% 概率为真的随机结果。"""
        ...
    def rFFFFFF(self) -> int:
        """返回 `[0, 0xFFFFFF)` 范围随机数。"""
        ...
    def rFFFF(self) -> int:
        """返回 `[0, 0xFFFF)` 范围随机数。"""
        ...
    def r256(self) -> int:
        """返回 `[0, 256)` 范围随机数。"""
        ...
    def r64(self) -> int:
        """返回 `[0, 64)` 范围随机数。"""
        ...
    def r16(self) -> int:
        """返回 `[0, 16)` 范围随机数。"""
        ...
    def r255(self) -> int:
        """返回 `[0, 255)` 范围随机数。"""
        ...
    def r127(self) -> int:
        """返回 `[0, 127)` 范围随机数。"""
        ...
    def r63(self) -> int:
        """返回 `[0, 63)` 范围随机数。"""
        ...
    def r31(self) -> int:
        """返回 `[0, 31)` 范围随机数。"""
        ...
    def r15(self) -> int:
        """返回 `[0, 15)` 范围随机数。"""
        ...
    def r7(self) -> int:
        """返回 `[0, 7)` 范围随机数。"""
        ...
    def r3(self) -> int:
        """返回 `[0, 3)` 范围随机数。"""
        ...
    def r3x3(self) -> int:
        """返回引擎内置的 `r3x3` 随机结果。"""
        ...
